spring:
       datasource:
                  url : jdbc:mysql://localhost/authserverdetail
                  username : root
                  password : root
                  driver-class-name : com.mysql.jdbc.Driver